blueprint:
  name: Rolladen auf
  description: Öffnet morgens einen Rolladen
  domain: automation
  input:
    device_rolladen:
      name: Rolladen
      description: Dieser Rolladen wird geöffnet
    zeitplan_rolladen_arbeitstag:
      name: Zeitplan
      description: Zeitplan des Rolladens für Arbeitstage
    zeitplan_rolladen:
        name: Zeitplan
        description: Zeitplan des Rolladens für andere Tage
    helligkeit:
      name: Mindest Helligkeit
      description: Dieser Wert muss überschritten werden um den Rolladen zu öffnen
      default: 40
      selector:
        number:
          min: 1.0
          max: 200.0
          unit_of_measurement: Lux
          mode: slider
          step: 10.0
trigger:
  - platform: numeric_state
    entity_id: sensor.koe11_helligkeit_30min_ha
    for:
      hours: 0
      minutes: 15
      seconds: 0
    above: !input helligkeit
  - platform: state
    entity_id:
      - !input zeitplan_rolladen
    from: "on"
    to: "off"
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.koe11_helligkeit_30min_ha
        above: !input helligkeit
      - condition: state
        entity_id: !input zeitplan_rolladen
        state: "off"
action:
  - entity_id: !inout device_rolladen
    type: set_position
    position: 100
mode: single