blueprint:
  name: Rolladen auf
  description: Öffnet morgens einen Rolladen
  source_url: https://github.com/akrauss/HAblue/edit/main/Rolladen_auf.yaml
  domain: automation
  input:
    device_rolladen:
      name: Rolladen
      description: Dieser Rolladen wird geöffnet
      selector:
          entity:
            domain: cover
    zeitplan_rolladen_arbeitstag:
      name: Zeitplan
      description: Zeitplan des Rolladens für Arbeitstage
      selector:
        text:
    zeitplan_rolladen:
      name: Zeitplan
      description: Zeitplan des Rolladens für andere Tage
      selector:
        text:
    helligkeit:
      name: Mindest Helligkeit
      description: Dieser Wert muss überschritten werden um den Rolladen zu öffnen
      default: 40
      selector:
        number:
          min: 0
          max: 200
trigger:

condition:

action:

mode: single
