blueprint:
  name: Rolladen Steuerung
  description: Steuert den Rolladen in einem Raum.
  source_url: https://github.com/akrauss/HAblue/blob/main/Rolladen.yaml
  domain: automation
  input:
    tag_section:
      name: Tag
      description: Einstellungen für Tag.
      input:
        szene_rolladen_tag:
          name: Szene Tag
          description: Szene für Rolladen am Tag.
          selector:
            entity:
              domain: scene
        zeitplan_rolladen_arbeitstag:
          name: Zeitplan Arbeitstag
          description: Zeitplan des Rolladens für Arbeitstage
          selector:
            entity:
              domain: schedule
        zeitplan_rolladen:
          name: Zeitplan
          description: Zeitplan des Rolladens für andere Tage
          selector:
            entity:
              domain: schedule
        helligkeit_tag:
          name: Mindest Helligkeit
          description: Dieser Wert muss überschritten werden um den Rolladen zu öffnen
          default: 40
          selector:
            number:
              min: 0
              max: 999
              unit_of_measurement: lux
    nacht_section:
      name: Nacht
      description: Einstellungen für Nacht.
      input:
        szene_rolladen_nacht:
          name: Szene Nacht
          description: Szene für Rolladen in der Nacht.
          selector:
            entity:
              domain: scene
        helligkeit_nacht:
          name: Maximal Helligkeit
          description: Dieser Wert muss unterschritten werden um den Rolladen zu schließen
          default: 30
          selector:
            number:
              min: 0
              max: 999
              unit_of_measurement: lux
    lueften_section:
      name: Lüftung
      description: Nachts Lüften, wenn Fenster offen.
      input:
        szene_rolladen_nacht_lueften:
          name: Szene Nacht Lüften
          description: Szene für Rolladen mit Lüften in der Nacht.
          selector:
            entity:
              domain: scene
        fenster_status:
          name: Entität der Fenster im Raum
          description: Fenster zum Rolladen
          selector:
            entity:
              device_class: window
    sunshade_section:
      name: Sonnenschutz
      description: Einstellungen für Sonnenschutz
      input:
        szene_rolladen_sonnenschutz:
          name: Szene Sonnenschutz
          description: Szene für Rolladen bei Sonnenschutz.
          selector:
            entity:
              domain: scene
        elevation_min:
          name: Elevation Min
          description: Mindesthöhe der Sonne über Horizont.
          selector:
            number:
              min: 0
              max: 90
              step: 5
              unit_of_measurement: "°"
              mode: slider
        azimuth_min:
          name: Azimuth Min
          description: Position der Sonne mindestens.
          selector:
            number:
              min: 0
              max: 360
              step: 10
              unit_of_measurement: "°"
              mode: slider
        azimuth_max:
          name: Azimuth Max
          description: Position der Sonne maximal.
          selector:
            number:
              min: 0
              max: 360
              step: 10
              unit_of_measurement: "°"
              mode: slider
trigger:
- platform: numeric_state
  entity_id: sensor.koe11_helligkeit_30min_ha
  for:
    hours: 0
    minutes: 15
    seconds: 0
  above: !input helligkeit_tag
- platform: numeric_state
  entity_id: sensor.koe11_helligkeit_30min_ha
  for:
    hours: 0
    minutes: 15
    seconds: 0
  below: !input helligkeit_nacht
- platform: numeric_state
  entity_id:
    - sensor.dwd_speyer_forcast_today_temperature
  for:
    hours: 0
    minutes: 15
    seconds: 0
  above: input_number.koe11_rolladen_temperatur_vorhersage_sonnenschutz
- platform: numeric_state
  entity_id:
    - sensor.koe11_weewx_aussentemperatur
  for:
    hours: 0
    minutes: 15
    seconds: 0
  above: input_number.koe11_rolladen_temperatur_sonnenschutz  
- platform: numeric_state
  entity_id:
    - sun.sun
  attribute: elevation
  above: !input elevation_min
- platform: numeric_state
  entity_id:
    - sun.sun
  attribute: azimuth
  above: !input azimuth_min
- platform: numeric_state
  entity_id:
    - sun.sun
  attribute: elevation
  below: !input azimuth_max
- platform: state
  entity_id:
  - !input zeitplan_rolladen
  from: 'on'
  to: 'off'
- platform: state
  entity_id:
  - !input zeitplan_rolladen_arbeitstag
  from: 'on'
  to: 'off'
- platform: state
  entity_id:
  - !input fenster_status
  from: 'on'
  to: 'off'
- platform: state
  entity_id:
  - !input fenster_status
  from: 'off'
  to: 'on'


condition: []
action:

## Sonnenschutz

  - if:
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.dwd_speyer_forcast_today_temperature
            above: input_number.koe11_rolladen_temperatur_vorhersage_sonnenschutz
          - condition: numeric_state
            entity_id: sensor.koe11_weewx_aussentemperatur
            above: input_number.koe11_rolladen_temperatur_sonnenschutz
        alias: Testen ob eine Temperatur überschritten
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: !input elevation_min
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: !input azimuth_min
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: !input azimuth_max
    then:
      - service: scene.turn_on
        target:
          entity_id: !input szene_rolladen_sonnenschutz
        data: {}
      - stop: "Sonnenschutz, beende Automation"  

## Tag

  - if:
    - condition: or
      conditions:
      - condition: and
        conditions:
        - condition: numeric_state
          entity_id: sensor.koe11_helligkeit_30min_ha
          above: !input helligkeit_tag
        - condition: state
          entity_id: !input zeitplan_rolladen
          state: 'off'
        - condition: state
          entity_id: input_boolean.koe11_arbeitstag
          state: "off"
      - condition: and
        conditions:
        - condition: numeric_state
          entity_id: sensor.koe11_helligkeit_30min_ha
          above: !input helligkeit_tag
        - condition: state
          entity_id: !input zeitplan_rolladen_arbeitstag
          state: 'off'
        - condition: state
          entity_id: input_boolean.koe11_arbeitstag
          state: "on"
    then:
      - service: scene.turn_on
        target:
          entity_id: !input szene_rolladen_tag
        data: {}
      - stop: "Tag, beende Automation"  

## Nacht mit Lüften

  - if:
    - condition: numeric_state
      entity_id: sensor.koe11_helligkeit_30min_ha
      below: !input helligkeit_nacht
    - condition: state
      entity_id: input_boolean.koe11_nachts_luften
      state: "on"
    - condition: state
      entity_id: !input fenster_status
      state: "on"
    then:
      - service: scene.turn_on
        target:
          entity_id: !input szene_rolladen_nacht_lueften
        data: {}
      - stop: "Nacht mit Lüften, beende Automation"  

## Nacht 

  - if:
    - condition: numeric_state
      entity_id: sensor.koe11_helligkeit_30min_ha
      below: !input helligkeit_nacht
    then:
      - service: scene.turn_on
        target:
          entity_id: !input szene_rolladen_nacht
        data: {}
      - stop: "Nacht, beende Automation"  

mode: single
